version: '3.8'

services:

  bios:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: bios

  validator1:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: validator1

  validator2:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: validator2

  validator3:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: validator3

  seed:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: seed

  api-node:
    image: v12node:${VERSION_NUMBER:-latest}
    build:
      target: v12_debug_node
      context: ./
      dockerfile: ./Dockerfile
    container_name: api-node



