version: '3.8'

networks:
  v12_testnet_external:
    external:
      name: v12_testnet_external
  v12_testnet_internal:
    external:
      name: v12_testnet_internal

secrets:
  V12_LOCALHOST_BIOS_PRIVATE_KEY:
    external: true
  V12_LOCALHOST_VALIDATOR1_PRIVATE_KEY:
    external: true
  V12_LOCALHOST_VALIDATOR2_PRIVATE_KEY:
    external: true
  V12_LOCALHOST_VALIDATOR3_PRIVATE_KEY:
    external: true

services:

  bios:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - bios
    secrets:
      - source: V12_LOCALHOST_BIOS_PRIVATE_KEY
        target: V12_BIOS_PRIVATE_KEY
    environment:
      EOS_PUB_KEY: EOS5xsW6nArVqhZkfMDj9T6sX8mJEvDGApDqBy6hCmg3dAxyuAEF3
      EOS_PRIV_KEY_FILE: /run/secrets/V12_BIOS_PRIVATE_KEY
      VERBOSE: "true"
    volumes:
      - ./services/bios:/opt/application

  validator1:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - validator1
    secrets:
      - source: V12_LOCALHOST_VALIDATOR1_PRIVATE_KEY
        target: V12_VALIDATOR1_PRIVATE_KEY
    environment:
      EOS_PUB_KEY: EOS6REpAwcReQm4TVYhzA8eyizonZMghdxymUBjQQgFCcSiNbkZWM
      EOS_PRIV_KEY_FILE: /run/secrets/V12_VALIDATOR1_PRIVATE_KEY
      VERBOSE: "true"
    volumes:
      - ./services/validator1:/opt/application

  validator2:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - validator2
    secrets:
      - source: V12_LOCALHOST_VALIDATOR2_PRIVATE_KEY
        target: V12_VALIDATOR2_PRIVATE_KEY
    environment:
      EOS_PUB_KEY: EOS7J1EdzcBTwGFUas1yn4XpSLc96jXESoSndtZDbCUV82n98NXVQ
      EOS_PRIV_KEY_FILE: /run/secrets/V12_VALIDATOR2_PRIVATE_KEY
      VERBOSE: "true"
    volumes:
      - ./services/validator2:/opt/application

  validator3:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - validator3
    secrets:
      - source: V12_LOCALHOST_VALIDATOR3_PRIVATE_KEY
        target: V12_VALIDATOR3_PRIVATE_KEY
    environment:
      EOS_PUB_KEY: EOS8cqtNw2RsHwZYvYVyARM4RWmDSGhrEncdSSPUEJwK2jeR37mit
      EOS_PRIV_KEY_FILE: /run/secrets/V12_VALIDATOR3_PRIVATE_KEY
      VERBOSE: "true"
    volumes:
      - ./services/validator3:/opt/application

  seed:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - seed
    environment:
      VERBOSE: "true"
    volumes:
      - ./services/seed:/opt/application

  api-node:
    image: registry.cybertron.ninja/v12node:${VERSION_NUMBER:-latest}
    networks:
      v12_testnet_external:
        aliases:
          - api-node
    environment:
      VERBOSE: "true"
    volumes:
      - ./services/api-node:/opt/application


